# Generated by Django 5.0.9 on 2026-08-22 05:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('phase', models.CharField(default='queued', max_length=64)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('source_key', models.CharField(max_length=1024)),
                ('sheet_name', models.CharField(blank=True, default='', max_length=255)),
                ('operation', models.CharField(choices=[('REPLACE', 'Replace matches with a fixed value'), ('MASK', 'Partially mask matches, keeping the pieces you choose'), ('EXTRACT', 'Extract matches into a new column'), ('VALIDATE', 'Flag rows whose value does not match')], default='REPLACE', max_length=16)),
                ('natural_language', models.TextField()),
                ('replacement_value', models.CharField(blank=True, default='', max_length=1024)),
                ('target_columns', models.JSONField(default=list)),
                ('force_refresh', models.BooleanField(default=False)),
                ('regex_pattern', models.TextField(blank=True, default='')),
                ('regex_case_insensitive', models.BooleanField(default=False)),
                ('replacement_template', models.CharField(blank=True, default='', max_length=512)),
                ('extract_group', models.PositiveSmallIntegerField(default=0)),
                ('llm_provider', models.CharField(blank=True, default='', max_length=32)),
                ('llm_model', models.CharField(blank=True, default='', max_length=64)),
                ('llm_explanation', models.TextField(blank=True, default='')),
                ('llm_confidence', models.FloatField(default=0.0)),
                ('llm_cached', models.BooleanField(default=False)),
                ('llm_warnings', models.JSONField(default=list)),
                ('self_test_passed', models.BooleanField(blank=True, null=True)),
                ('output_path', models.CharField(blank=True, default='', max_length=1024)),
                ('result_columns', models.JSONField(default=list)),
                ('page_index', models.JSONField(default=list)),
                ('total_rows', models.BigIntegerField(default=0)),
                ('matched_cells', models.BigIntegerField(default=0)),
                ('added_columns', models.JSONField(default=list)),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_type', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='jobs_job_status_57b86b_idx'), models.Index(fields=['source_key'], name='jobs_job_source__17bc9e_idx')],
            },
        ),
    ]
